name: Build and Package
on: [push]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'
    - name: Install dependencies
      run: npm i
    - name: Package
      run: npm run make
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: purerefAnimated
        path: |
          out/make/**/*.zip
          out/make/**/*.dmg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package for Linux
        run: npm run make

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: purerefAnimated-linux
          path: |
            out/make/**/*.(deb|rpm|flatpak)
  build-win-linux:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm i
      - name: Package
        run: npm run make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: purerefAnimated
          path: |
            out/make/**/*.zip
            out/make/**/*.exe